name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: srinirealty-webiste
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Create Artifact Registry repository (if it doesn't exist)
      run: |
        gcloud artifacts repositories create srinirealty-repo \
          --repository-format=docker \
          --location=us-central1 \
          --description="Docker repository for Srini Realty website" || true

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/srinirealty-repo/$SERVICE_NAME:$GITHUB_SHA .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/srinirealty-repo/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/srinirealty-repo/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars="NODE_ENV=production"

    - name: Get service URL
      run: |
        echo "Service URL: $(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')"
