name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: srinirealty-webiste
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Set gcloud project explicitly
      run: gcloud config set project $PROJECT_ID

    - name: Verify active service account
      run: gcloud auth list

    - name: Verify project
      run: gcloud config get-value project

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Verify Artifact Registry repo exists
      run: |
        gcloud artifacts repositories describe srinirealty-repo --location=us-central1

    - name: Build Docker image
      run: |
        IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/srinirealty-repo/$SERVICE_NAME:$GITHUB_SHA
        echo "Building image: $IMAGE_URI"
        docker build -t $IMAGE_URI .

    - name: Push Docker image
      run: |
        IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/srinirealty-repo/$SERVICE_NAME:$GITHUB_SHA
        echo "Pushing image: $IMAGE_URI"
        docker push $IMAGE_URI

    - name: Deploy to Cloud Run
      run: |
        IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/srinirealty-repo/$SERVICE_NAME:$GITHUB_SHA
        echo "Deploying to Cloud Run with image: $IMAGE_URI"
        gcloud run deploy $SERVICE_NAME \
          --image $IMAGE_URI \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars="NODE_ENV=production"

    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')
        echo "Service URL: $SERVICE_URL"
